"""Utility helpers for naming, AI completion, and text extraction."""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request


def to_snake(name: str) -> str:
    """Convert a script name to a safe lowercase_underscore identifier."""
    name = name.lower()
    name = re.sub(r'[^a-z0-9]+', '_', name)
    name = name.strip('_')
    return name or 'script'


def extract_code_block(text: str) -> str:
    """Extract Python code from markdown fences; fall back to raw text."""
    if not text:
        return ''
    m = re.search(r"```(?:python)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    return text.strip()


def load_text_file(path: str, max_chars: int = 120_000) -> str:
    try:
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            data = f.read(max_chars)
        return data
    except Exception:
        return ''


def ai_complete(provider: str, user_prompt: str, code: str, references: dict[str, str]) -> str:
    """Send a single-turn coding request to OpenAI or Anthropic and return text."""
    ref_sections = []
    for name, content in references.items():
        if content:
            ref_sections.append(f"### {name}\n{content}")
    refs_blob = "\n\n".join(ref_sections)

    system_prompt = (
        "You are helping edit a Python script generated by PyFlame UI Builder for Autodesk Flame. "
        "Use the reference stubs to keep API usage accurate. "
        "Return only updated Python code, no markdown, no explanation."
    )

    user_content = (
        f"Task:\n{user_prompt}\n\n"
        f"Current code:\n{code}\n\n"
        f"Reference stubs:\n{refs_blob}\n"
    )

    provider = (provider or '').lower().strip()
    if provider == 'openai':
        api_key = os.getenv('OPENAI_API_KEY', '').strip()
        if not api_key:
            raise RuntimeError('Missing OPENAI_API_KEY')
        model = os.getenv('PYFLAME_UI_BUILDER_OPENAI_MODEL', 'gpt-4o')
        payload = {
            'model': model,
            'temperature': 0.2,
            'messages': [
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': user_content},
            ],
        }
        req = urllib.request.Request(
            'https://api.openai.com/v1/chat/completions',
            data=json.dumps(payload).encode('utf-8'),
            headers={
                'Authorization': f'Bearer {api_key}',
                'Content-Type': 'application/json',
            },
            method='POST',
        )
        with urllib.request.urlopen(req, timeout=90) as resp:
            data = json.loads(resp.read().decode('utf-8', errors='ignore'))
        msg = data.get('choices', [{}])[0].get('message', {}).get('content', '')
        if isinstance(msg, list):
            msg = ''.join(part.get('text', '') for part in msg if isinstance(part, dict))
        return str(msg or '')

    if provider == 'claude':
        api_key = os.getenv('ANTHROPIC_API_KEY', '').strip()
        if not api_key:
            raise RuntimeError('Missing ANTHROPIC_API_KEY')
        model = os.getenv('PYFLAME_UI_BUILDER_CLAUDE_MODEL', 'claude-3-5-sonnet-latest')
        payload = {
            'model': model,
            'max_tokens': 4096,
            'temperature': 0.2,
            'system': system_prompt,
            'messages': [
                {'role': 'user', 'content': user_content},
            ],
        }
        req = urllib.request.Request(
            'https://api.anthropic.com/v1/messages',
            data=json.dumps(payload).encode('utf-8'),
            headers={
                'x-api-key': api_key,
                'anthropic-version': '2023-06-01',
                'content-type': 'application/json',
            },
            method='POST',
        )
        with urllib.request.urlopen(req, timeout=90) as resp:
            data = json.loads(resp.read().decode('utf-8', errors='ignore'))
        parts = data.get('content', [])
        text_bits = [p.get('text', '') for p in parts if isinstance(p, dict) and p.get('type') == 'text']
        return '\n'.join(t for t in text_bits if t)

    raise RuntimeError(f'Unsupported AI provider: {provider}')
