from __future__ import annotations
from typing import Any, overload

# Flame API stub for version: 2026.2

class PyActionFamilyNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_schematic(self, *args: Any, **kwargs: Any) -> bool: ...
    def connect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def create_node(self, node_type: str, file_path: str = ..., is_udim: bool = ..., tile_resolution: int = ..., input_colour_space: str = ...) -> Any: ...
    def disconnect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def encompass_nodes(self, node_list: list[Any]) -> Any: ...
    def get_node(self, node_name: str) -> PyNode: ...
    def organize(self, *args: Any, **kwargs: Any) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyActionNode(PyActionFamilyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_media(self, *args: Any, **kwargs: Any) -> Any: ...
    def disable_output(self, output_type: str) -> bool: ...
    def enable_output(self, output_type: str) -> bool: ...
    def export_fbx(self, file_path: str, only_selected_nodes: bool = ..., pixel_to_units: float = ..., frame_rate: str = ..., bake_animation: bool = ..., export_axes: bool = ..., export_point_locators: bool = ..., combine_material: bool = ..., duplicate_material: bool = ...) -> bool: ...
    def import_abc(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., frame_rate: str = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., consolidate_geometry: bool = ..., create_object_group: bool = ...) -> list[Any]: ...
    def import_fbx(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., keep_frame_rate: bool = ..., bake_animation: bool = ..., object_properties: bool = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., create_media: bool = ..., is_udim: bool = ..., relink_material: bool = ..., input_colour_space: str = ...) -> list[Any]: ...
    def import_psd(self, file_path: str, input_colour_space: str = ...) -> list[Any]: ...
    def read_abc(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., frame_rate: str = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., consolidate_geometry: bool = ..., create_object_group: bool = ...) -> Any: ...
    def read_fbx(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., keep_frame_rate: bool = ..., bake_animation: bool = ..., object_properties: bool = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., is_udim: bool = ..., relink_material: bool = ..., input_colour_space: str = ...) -> Any: ...
    def clear_schematic(self, *args: Any, **kwargs: Any) -> bool: ...
    def connect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def create_node(self, node_type: str, file_path: str = ..., is_udim: bool = ..., tile_resolution: int = ..., input_colour_space: str = ...) -> Any: ...
    def disconnect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def encompass_nodes(self, node_list: list[Any]) -> Any: ...
    def get_node(self, node_name: str) -> PyNode: ...
    def organize(self, *args: Any, **kwargs: Any) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyArchiveEntry(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyAttribute(object):
    def __add__(self, arg2: float) -> Any: ...
    def __eq__(self, arg2: Any) -> bool: ...
    def __floordiv__(self, arg2: Any) -> Any: ...
    def __ge__(self, arg2: float) -> Any: ...
    def __gt__(self, arg2: float) -> Any: ...
    def __iadd__(self, arg2: float) -> Any: ...
    def __idiv__(self, arg2: float) -> Any: ...
    def __imul__(self, arg2: float) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __isub__(self, arg2: float) -> Any: ...
    def __le__(self, arg2: float) -> Any: ...
    def __lt__(self, arg2: float) -> Any: ...
    def __mul__(self, arg2: float) -> Any: ...
    def __ne__(self, arg2: Any) -> bool: ...
    def __radd__(self, arg2: float) -> Any: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __rmul__(self, arg2: float) -> Any: ...
    def __rsub__(self, arg2: float) -> Any: ...
    def __rtruediv__(self, arg2: float) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> str: ...
    def __sub__(self, arg2: float) -> Any: ...
    def __truediv__(self, arg2: float) -> Any: ...
    def get_value(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_value(self, arg2: Any) -> bool: ...

class PyAudioTrack(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyBatch(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def append_setup(self, setup_path: str, confirm: bool = ...) -> bool: ...
    def append_to_batch(self, batch_iteration: PyBatchIteration) -> bool: ...
    def append_to_setup(self, batch_iteration: PyBatchIteration) -> bool: ...
    def clear(self, confirm: bool = ...) -> bool: ...
    def clear_all_contexts(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_context(self, index: int) -> bool: ...
    def clear_setup(self, *args: Any, **kwargs: Any) -> bool: ...
    def close(self, *args: Any, **kwargs: Any) -> bool: ...
    def connect_nodes(self, output_node: PyNode, output_socket_name: str = ..., input_node: PyNode, input_socket_name: str = ...) -> bool: ...
    def create_batch_group(self, name: str, nb_reels: Any = ..., nb_shelf_reels: Any = ..., reels: list[Any] = ..., shelf_reels: list[Any] = ..., start_frame: int = ..., duration: Any = ...) -> Any: ...
    def create_node(self, node_type: str, file_path: str = ...) -> Any: ...
    def create_reel(self, name: str) -> PyReel: ...
    def create_shelf_reel(self, name: str) -> Any: ...
    def disconnect_node(self, node: PyNode, input_socket_name: str = ...) -> bool: ...
    def encompass_nodes(self, nodes: list[Any]) -> Any: ...
    def frame_all(self, *args: Any, **kwargs: Any) -> bool: ...
    def frame_selected(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_node(self, node_name: str) -> PyNode: ...
    def go_to(self, *args: Any, **kwargs: Any) -> bool: ...
    def import_clip(self, file_path: str, reel_name: str) -> PyClip: ...
    def import_clips(self, file_paths: Any, reel_name: str) -> list[PyClip]: ...
    def iterate(self, index: int = ...) -> PyBatchIteration: ...
    def load_setup(self, setup_path: str) -> bool: ...
    def mimic_link(self, leader_node: PyNode, follower_node: PyNode) -> bool: ...
    def open(self, *args: Any, **kwargs: Any) -> bool: ...
    def open_as_batch_group(self, confirm: bool = ...) -> bool: ...
    def organize(self, *args: Any, **kwargs: Any) -> bool: ...
    def render(self, render_option: str = ..., generate_proxies: bool = ..., include_history: bool = ...) -> bool: ...
    def replace_setup(self, batch_iteration: PyBatchIteration, confirm: bool = ...) -> bool: ...
    def save(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_current_iteration(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_setup(self, setup_path: str) -> bool: ...
    def select_nodes(self, nodes: Any) -> bool: ...
    def set_viewport_layout(self, num_views: Any) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyBatchIteration(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def open_as_batch_group(self, confirm: bool = ...) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyBrowser(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def show(self, default_path: str, extension: Any = ..., select_directory: bool = ..., multi_selection: bool = ..., include_resolution: Any = ..., title: str = ...) -> None: ...

class PyClip(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cache_media(self, mode: str = ...) -> bool: ...
    def change_dominance(self, scan_mode: str) -> None: ...
    def change_start_frame(self, start_frame: int, use_segment_connections: bool = ...) -> None: ...
    def close_container(self, *args: Any, **kwargs: Any) -> None: ...
    def create_marker(self, location: Any) -> PyMarker: ...
    def cut(self, cut_time: PyTime) -> None: ...
    def flush_cache_media(self, mode: str = ...) -> bool: ...
    def flush_renders(self, *args: Any, **kwargs: Any) -> None: ...
    def get_colour_space(self, time: PyTime = ...) -> str: ...
    def is_rendered(self, top_only: bool = ..., render_quality: str = ...) -> bool: ...
    def open_as_sequence(self, *args: Any, **kwargs: Any) -> PySequence: ...
    def open_container(self, *args: Any, **kwargs: Any) -> bool: ...
    def reformat(self, width: int = ..., height: int = ..., ratio: float = ..., bit_depth: int = ..., scan_mode: str = ..., frame_rate: str = ..., resize_mode: str = ...) -> None: ...
    def render(self, render_mode: str = ..., render_option: str = ..., render_quality: str = ..., effect_type: str = ..., effect_caching_mode: str = ..., include_handles: bool = ...) -> bool: ...
    def save(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyClipNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_version_uid(self, version_uid: str) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyClrMgmtNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_context_variables(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def import_transform(self, file_path: str) -> None: ...
    def reset_context_variables(self, *args: Any, **kwargs: Any) -> None: ...
    def set_context_variable(self, name: str, value: str) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyCoCameraAnalysis(PyCoNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def analyseRange(self, arg2: Any, start: Any) -> bool: ...
    def resetAnalysis(self, *args: Any, **kwargs: Any) -> bool: ...
    def add_reference(self, frame: Any) -> bool: ...
    def assign_media(self, media_name: Any) -> bool: ...
    def cache_range(self, arg2: Any, start: Any) -> bool: ...
    def children(self, link_type: str = ...) -> list[Any]: ...
    def parents(self, link_type: str = ...) -> list[Any]: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyCoCompass(PyCoNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_reference(self, frame: Any) -> bool: ...
    def assign_media(self, media_name: Any) -> bool: ...
    def cache_range(self, arg2: Any, start: Any) -> bool: ...
    def children(self, link_type: str = ...) -> list[Any]: ...
    def parents(self, link_type: str = ...) -> list[Any]: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyCoNode(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_reference(self, frame: Any) -> bool: ...
    def assign_media(self, media_name: Any) -> bool: ...
    def cache_range(self, arg2: Any, start: Any) -> bool: ...
    def children(self, link_type: str = ...) -> list[Any]: ...
    def parents(self, link_type: str = ...) -> list[Any]: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyColourMgtTimelineFX(PyTimelineFX):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_context_variables(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def import_transform(self, file_path: str) -> None: ...
    def reset_context_variables(self, *args: Any, **kwargs: Any) -> None: ...
    def set_context_variable(self, name: str, value: str) -> None: ...
    def flush_maps_cache_media(self, *args: Any, **kwargs: Any) -> bool: ...
    def load_setup(self, file_name: str) -> bool: ...
    def save_setup(self, file_name: str) -> bool: ...
    def slide_keyframes(self, offset: float) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyCompassNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyDesktop(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, *args: Any, **kwargs: Any) -> bool: ...
    def create_batch_group(self, name: str, nb_reels: Any = ..., nb_shelf_reels: Any = ..., reels: list[Any] = ..., shelf_reels: list[Any] = ..., start_frame: int = ..., duration: Any = ...) -> Any: ...
    def create_reel_group(self, name: str) -> PyReelGroup: ...
    def save(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyExporter(object):
    export_all_subtitles: Any
    export_between_marks: Any
    export_subtitles_as_files: Any
    foreground: Any
    include_subtitles: Any
    keep_timeline_fx_renders: Any
    use_top_video_track: Any
    warn_on_mixed_colour_space: Any
    warn_on_no_media: Any
    warn_on_pending_render: Any
    warn_on_reimport_unsupported: Any
    warn_on_unlinked: Any
    warn_on_unrendered: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def export(self, sources: Any, preset_path: str, output_directory: str, background_job_settings: Any = ..., hooks: Any = ..., hooks_user_data: Any = ...) -> None: ...
    def get_presets_base_dir(self, preset_visibility: Any) -> str: ...
    def get_presets_dir(self, preset_visibility: Any, preset_type: Any) -> str: ...

class PyFlameObject(object):
    def __getattr__(self, arg2: str) -> Any: ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyFolder(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, confirm: bool = ...) -> bool: ...
    def create_folder(self, name: str) -> PyFolder: ...
    def create_reel(self, name: str) -> PyReel: ...
    def create_reel_group(self, name: str) -> PyReelGroup: ...
    def create_sequence(self, name: str = ..., video_tracks: int = ..., video_stereo: bool = ..., width: Any = ..., height: Any = ..., ratio: Any = ..., bit_depth: Any = ..., scan_mode: Any = ..., frame_rate: Any = ..., start_at: Any = ..., duration: Any = ..., audio_tracks: int = ..., audio_stereo: bool = ...) -> PySequence: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyGMaskTracerNode(PyActionFamilyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def disable_output(self, output_type: str) -> bool: ...
    def enable_output(self, output_type: str) -> bool: ...
    def export_fbx(self, file_path: str, only_selected_nodes: bool = ..., pixel_to_units: float = ..., frame_rate: str = ..., bake_animation: bool = ..., export_axes: bool = ..., export_point_locators: bool = ..., combine_material: bool = ..., duplicate_material: bool = ...) -> bool: ...
    def import_abc(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., frame_rate: str = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., consolidate_geometry: bool = ..., create_object_group: bool = ...) -> list[Any]: ...
    def import_fbx(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., keep_frame_rate: bool = ..., bake_animation: bool = ..., object_properties: bool = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., create_media: bool = ..., is_udim: bool = ..., relink_material: bool = ..., input_colour_space: str = ...) -> list[Any]: ...
    def import_psd(self, file_path: str, input_colour_space: str = ...) -> list[Any]: ...
    def read_abc(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., frame_rate: str = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., consolidate_geometry: bool = ..., create_object_group: bool = ...) -> Any: ...
    def read_fbx(self, file_path: str, lights: bool = ..., cameras: bool = ..., models: bool = ..., normals: bool = ..., mesh_animations: bool = ..., keep_frame_rate: bool = ..., bake_animation: bool = ..., object_properties: bool = ..., auto_fit: bool = ..., unit_to_pixels: float = ..., is_udim: bool = ..., relink_material: bool = ..., input_colour_space: str = ...) -> Any: ...
    def clear_schematic(self, *args: Any, **kwargs: Any) -> bool: ...
    def connect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def create_node(self, node_type: str, file_path: str = ..., is_udim: bool = ..., tile_resolution: int = ..., input_colour_space: str = ...) -> Any: ...
    def disconnect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def encompass_nodes(self, node_list: list[Any]) -> Any: ...
    def get_node(self, node_name: str) -> PyNode: ...
    def organize(self, *args: Any, **kwargs: Any) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyHDRNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def analyze(self, analyze_mode: str = ...) -> None: ...
    def export_DolbyVision_xml(self, file_name: str, comment: str = ...) -> None: ...
    def has_trim(self, target_display_id: int) -> bool: ...
    def import_DolbyVision_xml(self, file_name: str, mode: str = ..., shot_idx: int = ...) -> None: ...
    def interpolate_trims(self, *args: Any, **kwargs: Any) -> None: ...
    def keep_analysis(self, *args: Any, **kwargs: Any) -> None: ...
    def l2_from_l8(self, *args: Any, **kwargs: Any) -> Any: ...
    def reset_analysis(self, *args: Any, **kwargs: Any) -> None: ...
    def reset_trims(self, *args: Any, **kwargs: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyHDRTimelineFX(PyTimelineFX):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def analyze(self, analyze_mode: str = ...) -> None: ...
    def export_DolbyVision_xml(self, file_name: str, shot_only: bool = ..., comment: str = ...) -> None: ...
    def has_trim(self, target_display_id: int) -> bool: ...
    def import_DolbyVision_xml(self, file_name: str, mode: str = ..., shot_idx: int = ...) -> None: ...
    def interpolate_trims(self, arg2: str) -> None: ...
    def keep_analysis(self, *args: Any, **kwargs: Any) -> None: ...
    def l2_from_l8(self, *args: Any, **kwargs: Any) -> Any: ...
    def reset_analysis(self, *args: Any, **kwargs: Any) -> None: ...
    def reset_trims(self, *args: Any, **kwargs: Any) -> None: ...
    def flush_maps_cache_media(self, *args: Any, **kwargs: Any) -> bool: ...
    def load_setup(self, file_name: str) -> bool: ...
    def save_setup(self, file_name: str) -> bool: ...
    def slide_keyframes(self, offset: float) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyImageNode(PyActionFamilyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_media(self, *args: Any, **kwargs: Any) -> Any: ...
    def clear_schematic(self, *args: Any, **kwargs: Any) -> bool: ...
    def connect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def create_node(self, node_type: str, file_path: str = ..., is_udim: bool = ..., tile_resolution: int = ..., input_colour_space: str = ...) -> Any: ...
    def disconnect_nodes(self, parent_node: PyFlameObject, child_node: PyFlameObject, link_type: str = ...) -> bool: ...
    def encompass_nodes(self, node_list: list[Any]) -> Any: ...
    def get_node(self, node_name: str) -> PyNode: ...
    def organize(self, *args: Any, **kwargs: Any) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyLensDistortionNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def calculate(self, *args: Any, **kwargs: Any) -> None: ...
    def import_lens_distortion(self, filename: str) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyLibrary(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def acquire_exclusive_access(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear(self, confirm: bool = ...) -> bool: ...
    def close(self, *args: Any, **kwargs: Any) -> bool: ...
    def create_folder(self, name: str) -> PyFolder: ...
    def create_reel(self, name: str) -> PyReel: ...
    def create_reel_group(self, name: str) -> PyReelGroup: ...
    def create_sequence(self, name: str = ..., video_tracks: int = ..., video_stereo: bool = ..., width: Any = ..., height: Any = ..., ratio: Any = ..., bit_depth: Any = ..., scan_mode: Any = ..., frame_rate: Any = ..., start_at: Any = ..., duration: Any = ..., audio_tracks: int = ..., audio_stereo: bool = ...) -> PySequence: ...
    def open(self, *args: Any, **kwargs: Any) -> bool: ...
    def release_exclusive_access(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMarker(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMediaHub(object):
    archives: Any
    files: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyMediaHubFilesEntry(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMediaHubFilesFolder(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMediaHubFilesTab(PyMediaHubTab):
    options: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_path(self, *args: Any, **kwargs: Any) -> str: ...
    def set_path(self, arg2: str, allow_partial_success: bool = ...) -> bool: ...

class PyMediaHubFilesTabOptions(object):
    bit_depth: int
    cache_and_proxies_all_versions: Any
    cache_mode: Any
    frame_ratio: Any
    height: int
    multi_channel_mode: Any
    pixel_ratio: Any
    proxies_mode: Any
    resize_filter: Any
    resize_mode: Any
    resolution: Any
    scaling_presets_value: Any
    scan_mode: str
    sequence_mode: Any
    width: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_tagged_colour_space(self, colour_space: str) -> None: ...

class PyMediaHubProjectsEntry(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMediaHubProjectsFolder(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyMediaHubTab(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_path(self, *args: Any, **kwargs: Any) -> str: ...
    def set_path(self, arg2: str, allow_partial_success: bool = ...) -> bool: ...

class PyMediaPanel(object):
    dual: Any
    full_height: Any
    full_width: Any
    selected_entries: Any
    visible: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy(self, source_entries: Any, destination: Any, duplicate_action: str = ...) -> Any: ...
    def move(self, source_entries: Any, destination: Any, duplicate_action: str = ...) -> Any: ...

class PyMessages(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_console(self, *args: Any, **kwargs: Any) -> None: ...
    def show_in_console(self, message: str, type: str = ..., duration: int = ...) -> None: ...
    def show_in_dialog(self, title: str, message: str, type: str, buttons: list[Any], cancel_button: str = ...) -> str: ...

class PyMorphNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_mix_to_range(self, *args: Any, **kwargs: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyNode(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyOFXNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def change_plugin(self, plugin_name: str) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyPaintNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_source(self, *args: Any, **kwargs: Any) -> Any: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyProject(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_shared_library(self, name: str) -> Any: ...
    def export_ocio_config(self, config_name: str, destination_folder: str = ..., overwrite_existing: bool = ..., export_as_locked: bool = ..., generate_ocioz: bool = ...) -> bool: ...
    def get_context_variables(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def refresh_shared_libraries(self, *args: Any, **kwargs: Any) -> bool: ...
    def reload_ocio_config(self, reset_colour_policy: bool = ...) -> bool: ...
    def reset_context_variables(self, *args: Any, **kwargs: Any) -> None: ...
    def set_context_variable(self, name: str, value: str) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyProjectSelector(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyReel(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, confirm: bool = ...) -> bool: ...
    def create_sequence(self, name: str = ..., video_tracks: int = ..., video_stereo: bool = ..., width: Any = ..., height: Any = ..., ratio: Any = ..., bit_depth: Any = ..., scan_mode: Any = ..., frame_rate: Any = ..., start_at: Any = ..., duration: Any = ..., audio_tracks: int = ..., audio_stereo: bool = ...) -> PySequence: ...
    def save(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyReelGroup(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def clear(self, confirm: bool = ...) -> bool: ...
    def create_reel(self, name: str, sequence: bool = ...) -> PyReel: ...
    def save(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyRenderNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_channel_name(self, channel: Any, name: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyResolution(object):
    bit_depth: int
    frame_ratio: Any
    height: int
    resolution: Any
    scan_mode: str
    width: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PySearch(object):
    use_weight: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def activate_search_result(self, name: str, type: str, tab: str = ...) -> None: ...
    def search_results(self, search_str: str = ..., tab: str = ...) -> list[Any]: ...
    def set_tool_favorite(self, arg2: str, name: str, type: bool) -> None: ...
    def set_tool_hidden(self, arg2: str, name: str, type: bool) -> None: ...
    def set_tool_weight(self, arg2: str, name: str, type: int) -> None: ...

class PySegment(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def change_start_frame(self, start_frame: int, use_segment_connections: bool = ...) -> None: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def connected_segments(self, scoping: str = ...) -> Any: ...
    def copy_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def create_connection(self, *args: Any, **kwargs: Any) -> None: ...
    def create_effect(self, effect_type: str, after_effect_type: str = ...) -> Any: ...
    def create_marker(self, location: Any) -> PyMarker: ...
    def create_unlinked_segment(self, source_name: str = ..., tape_name: str = ..., start_time: Any = ..., source_duration: Any = ..., head: Any = ..., file_path: str = ..., source_audio_track: int = ..., width: int = ..., height: int = ..., ratio: float = ..., bit_depth: int = ..., scan_mode: str = ..., frame_rate: str = ...) -> None: ...
    def duplicate_source(self, *args: Any, **kwargs: Any) -> None: ...
    def get_colour_space(self, time: PyTime = ...) -> str: ...
    def match(self, destination: PyArchiveEntry, preserve_handle: bool = ..., use_sequence_info: bool = ..., include_nested_content: bool = ..., include_timeline_fx: bool = ...) -> Any: ...
    def remove_connection(self, *args: Any, **kwargs: Any) -> None: ...
    def set_gap_bars(self, type: str = ..., full_luminance: bool = ..., softness: float = ...) -> Any: ...
    def set_gap_colour(self, r: float = ..., g: float = ..., b: float = ...) -> None: ...
    def set_matte_channel(self, channel_name: str = ..., channel_index: int = ..., scope: str = ..., matte_mode: str = ...) -> bool: ...
    def set_rgb_channel(self, channel_name: str = ..., channel_index: int = ..., scope: str = ...) -> bool: ...
    def set_version_uid(self, version_uid: str, scope: str = ...) -> bool: ...
    def shared_source_segments(self, *args: Any, **kwargs: Any) -> Any: ...
    def slide_keyframes(self, offset: int, sync: bool = ...) -> bool: ...
    def slip(self, offset: int, sync: bool = ..., keyframes_move_mode: str = ...) -> bool: ...
    def smart_replace(self, source_clip: PyClip) -> None: ...
    def smart_replace_media(self, source_clip: PyClip) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def trim_head(self, offset: int, ripple: bool = ..., sync: bool = ..., keyframes_move_mode: str = ...) -> bool: ...
    def trim_tail(self, offset: int, ripple: bool = ..., sync: bool = ..., keyframes_move_mode: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PySequence(PyClip):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy_selection_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def create_audio(self, stereo: bool = ...) -> Any: ...
    def create_container(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_group(self, name: str) -> Any: ...
    def create_subtitle(self, *args: Any, **kwargs: Any) -> Any: ...
    def create_version(self, stereo: bool = ...) -> Any: ...
    def extract_selection_to_media_panel(self, destination: PyArchiveEntry = ..., duplicate_action: str = ...) -> Any: ...
    def import_subtitles_file(self, file_name: str, file_type: Any = ..., align_first_event_to_clip_start: bool = ..., convert_from_frame_rate: Any = ...) -> Any: ...
    def insert(self, source_clip: PyClip, insert_time: PyTime = ..., destination_track: PyTrack = ...) -> bool: ...
    def lift_selection_to_media_panel(self, destination: PyArchiveEntry = ..., duplicate_action: str = ...) -> Any: ...
    def open(self, *args: Any, **kwargs: Any) -> bool: ...
    def overwrite(self, source_clip: PyClip, overwrite_time: PyTime = ..., destination_track: PyTrack = ...) -> bool: ...
    def cache_media(self, mode: str = ...) -> bool: ...
    def change_dominance(self, scan_mode: str) -> None: ...
    def change_start_frame(self, start_frame: int, use_segment_connections: bool = ...) -> None: ...
    def close_container(self, *args: Any, **kwargs: Any) -> None: ...
    def create_marker(self, location: Any) -> PyMarker: ...
    def cut(self, cut_time: PyTime) -> None: ...
    def flush_cache_media(self, mode: str = ...) -> bool: ...
    def flush_renders(self, *args: Any, **kwargs: Any) -> None: ...
    def get_colour_space(self, time: PyTime = ...) -> str: ...
    def is_rendered(self, top_only: bool = ..., render_quality: str = ...) -> bool: ...
    def open_as_sequence(self, *args: Any, **kwargs: Any) -> PySequence: ...
    def open_container(self, *args: Any, **kwargs: Any) -> bool: ...
    def reformat(self, width: int = ..., height: int = ..., ratio: float = ..., bit_depth: int = ..., scan_mode: str = ..., frame_rate: str = ..., resize_mode: str = ...) -> None: ...
    def render(self, render_mode: str = ..., render_option: str = ..., render_quality: str = ..., effect_type: str = ..., effect_caching_mode: str = ..., include_handles: bool = ...) -> bool: ...
    def save(self, *args: Any, **kwargs: Any) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PySequenceGroup(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add(self, segments: Any) -> None: ...
    def remove(self, segments: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PySubtitleTrack(PyTrack):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def export_as_srt_file(self, file_name: str, character_based_attributes: bool = ..., export_colours: bool = ..., exclude_colour: str = ..., use_original_colours: bool = ..., use_original_alignment: bool = ..., export_alignments: bool = ..., alignment_type: str = ..., exclude_alignment: str = ..., start_timecode: str = ...) -> None: ...
    def copy_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def cut(self, cut_time: PyTime, sync: bool = ...) -> None: ...
    def insert_transition(self, record_time: PyTime, type: str, duration: int = ..., alignment: str = ..., in_offset: int = ..., sync: bool = ...) -> Any: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTime(object):
    def __add__(self, arg2: PyTime) -> Any: ...
    def __eq__(self, arg2: PyTime) -> bool: ...
    def __iadd__(self, arg2: PyTime) -> Any: ...
    def __init__(self, arg2: str, arg3: str) -> None: ...
    def __isub__(self, arg2: PyTime) -> Any: ...
    def __ne__(self, arg2: PyTime) -> bool: ...
    def __repr__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __str__(self, *args: Any, **kwargs: Any) -> str: ...
    def __sub__(self, arg2: PyTime) -> Any: ...

class PyTimeline(object):
    type: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyTimelineFX(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def flush_maps_cache_media(self, *args: Any, **kwargs: Any) -> bool: ...
    def load_setup(self, file_name: str) -> bool: ...
    def save_setup(self, file_name: str) -> bool: ...
    def slide_keyframes(self, offset: float) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTimewarpNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_duration_timing(self, frame: float) -> float: ...
    def get_speed(self, frame: float) -> float: ...
    def get_speed_timing(self, frame: float) -> float: ...
    def get_timing(self, frame: float) -> float: ...
    def set_speed(self, frame: float, new_speed: float) -> None: ...
    def set_timing(self, frame: float, new_timing: float) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTimewarpTimelineFX(PyTimelineFX):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_duration_timing(self, frame: float) -> float: ...
    def get_speed(self, frame: float) -> float: ...
    def get_speed_timing(self, frame: float) -> float: ...
    def get_timing(self, frame: float) -> float: ...
    def set_speed(self, frame: float, new_speed: float) -> None: ...
    def set_timing(self, frame: float, new_timing: float) -> None: ...
    def flush_maps_cache_media(self, *args: Any, **kwargs: Any) -> bool: ...
    def load_setup(self, file_name: str) -> bool: ...
    def save_setup(self, file_name: str) -> bool: ...
    def slide_keyframes(self, offset: float) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTrack(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def cut(self, cut_time: PyTime, sync: bool = ...) -> None: ...
    def insert_transition(self, record_time: PyTime, type: str, duration: int = ..., alignment: str = ..., in_offset: int = ..., sync: bool = ...) -> Any: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTransition(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_dissolve_to_from_colour(self, r: float = ..., g: float = ..., b: float = ...) -> None: ...
    def set_fade_to_from_silence(self, *args: Any, **kwargs: Any) -> None: ...
    def set_transition(self, type: str, duration: int = ..., alignment: str = ..., in_offset: int = ...) -> Any: ...
    def slide(self, offset: int, sync: bool = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTypeFX(PyTimelineFX):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_layer(self, layer_type: str = ...) -> Any: ...
    def append_type_setup(self, file_name: str) -> bool: ...
    def flush_maps_cache_media(self, *args: Any, **kwargs: Any) -> bool: ...
    def load_setup(self, file_name: str) -> bool: ...
    def save_setup(self, file_name: str) -> bool: ...
    def slide_keyframes(self, offset: float) -> None: ...
    def sync_connected_segments(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTypeLayer(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyTypeNode(PyNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_layer(self, layer_type: str = ...) -> Any: ...
    def append_type_setup(self, file_name: str) -> bool: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyUser(object):
    shortcuts_profile: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyUsers(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class PyVersion(PyFlameObject):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def copy_to_media_panel(self, destination: PyArchiveEntry, duplicate_action: str = ...) -> Any: ...
    def create_track(self, track_index: int = ..., hdr: bool = ...) -> Any: ...
    def import_DolbyVision_xml(self, file_name: str, mode: str = ..., track_index: int = ...) -> Any: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyWorkspace(PyArchiveEntry):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def create_library(self, name: str) -> Any: ...
    def replace_desktop(self, desktop: PyDesktop) -> bool: ...
    def set_desktop_reels(self, group: Any = ...) -> bool: ...
    def set_freeform(self, reel: Any = ...) -> bool: ...
    def clear_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def commit(self, *args: Any, **kwargs: Any) -> None: ...
    def get_wiretap_node_id(self, *args: Any, **kwargs: Any) -> str: ...
    def get_wiretap_storage_id(self, *args: Any, **kwargs: Any) -> str: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

class PyWriteFileNode(PyRenderNode):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_resolved_media_path(self, show_extension: bool = ..., translate_path: bool = ..., frame: Any = ...) -> Any: ...
    def set_channel_name(self, channel: Any, name: Any) -> None: ...
    def cache_range(self, start: Any = ..., end: Any = ...) -> int: ...
    def clear_schematic_colour(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self, confirm: bool = ...) -> bool: ...
    def duplicate(self, keep_node_connections: bool = ...) -> Any: ...
    def load_node_setup(self, file_name: str) -> bool: ...
    def save_node_setup(self, file_name: str) -> bool: ...
    def set_context(self, index: int, socket_name: str = ...) -> bool: ...
    def __getattr__(self, arg2: str) -> Any: ...
    def __setattr__(self, arg2: str, arg3: Any) -> None: ...

# Module-level functions
def delete(object: PyFlameObject, confirm: bool = ...) -> bool: ...
def duplicate(object: PyFlameObject, keep_node_connections: bool = ...) -> Any: ...
def duplicate_many(object_list: list[Any], keep_node_connections: bool = ...) -> list[Any]: ...
def execute_command(command: str, blocking: bool = ..., shell: bool = ..., capture_stdout: bool = ..., capture_stderr: bool = ...) -> tuple[Any, ...]: ...
def execute_shortcut(description: str, update_list: bool = ...) -> bool: ...
def exit(*args: Any, **kwargs: Any) -> None: ...
def find_by_name(name: str, parent: Any = ...) -> list[Any]: ...
def find_by_uid(uid: str) -> Any: ...
def find_by_wiretap_node_id(node_id: str) -> Any: ...
def flush_graphics_memory(*args: Any, **kwargs: Any) -> None: ...
def get_current_tab(*args: Any, **kwargs: Any) -> str: ...
def get_home_directory(*args: Any, **kwargs: Any) -> str: ...
def get_init_cfg_path(*args: Any, **kwargs: Any) -> str: ...
def get_version(*args: Any, **kwargs: Any) -> str: ...
def get_version_major(*args: Any, **kwargs: Any) -> str: ...
def get_version_minor(*args: Any, **kwargs: Any) -> str: ...
def get_version_patch(*args: Any, **kwargs: Any) -> str: ...
def get_version_stamp(*args: Any, **kwargs: Any) -> str: ...
def go_to(tab: str) -> bool: ...
def import_clips(path: Any, destination: Any = ...) -> list[PyClip]: ...
def schedule_idle_event(function: Any, delay: int = ...) -> None: ...
def set_current_tab(arg1: str) -> bool: ...
def set_render_option(render_option: str, render_context: str = ...) -> bool: ...

# Module-level data
batch: Any
browser: Any
media_panel: Any
mediahub: Any
messages: Any
project: Any
projects: Any
timeline: Any
users: Any
