# Auto-generated stub file.
# Source of truth: Python implementation file.
# Regenerate with: python3 generate_stubs.py

from __future__ import annotations
from typing import Any, Callable, Iterable, Iterator, Sequence, Mapping

LIB_PATH: Any
SCRIPT_NAME: Any
SCRIPT_PATH: Any
SHARED_FILE_SEQUENCE_PATH: Any
SHARED_MOVIE_EXPORT_PATH: Any
# Color
class Color(Enum):
    BLUE: Any
    RED: Any
    YELLOW: Any
    GREEN: Any
    TEAL: Any
    BLUE_TRANS: Any
    RED_TRANS: Any
    YELLOW_TRANS: Any
    GREEN_TRANS: Any
    TEAL_TRANS: Any
    GRAY: Any
    DARK_GRAY: Any
    BRIGHT_GRAY: Any
    BLACK: Any
    WHITE: Any
    TEXT: Any
    TEXT_BRIGHT: Any
    TEXT_SELECTED: Any
    TEXT_DISABLED: Any
    TEXT_UNDERLINE: Any
    TEXT_BORDER: Any
    TEXT_READ_ONLY_BACKGROUND: Any
    BUTTON_TEXT: Any
    SELECTED_GRAY: Any
    BORDER: Any
    BORDER_BRIGHTER: Any
    UNDERLINE: Any
    ENTRY_GRAY: Any
    DISABLED_GRAY: Any
    ITEM_BACKGROUND_COLOR: Any
    ITEM_ALT_BACKGROUND_COLOR: Any
    PUSHBUTTON_BLUE: Any
    PUSHBUTTON_BLUE_CHECKED: Any
    PUSHBUTTON_BLUE_DISABLED: Any
    TAB_PANE: Any
    SCROLLBAR_HANDLE: Any

# TextColor
class TextColor(Enum):
    GREEN: Any
    YELLOW: Any
    RED: Any
    WHITE: Any
    BLUE: Any
    RESET: Any
    # Format the given text with the Enum's color.
    def format(self, text: str) -> str: ...

# Style
class Style(Enum):
    NORMAL: Any
    UNDERLINE: Any
    BORDER: Any
    BACKGROUND: Any
    BACKGROUND_THIN: Any

# Align
class Align(Enum):
    LEFT: Any
    RIGHT: Any
    CENTER: Any

# MessageType
class MessageType(Enum):
    INFO: Any
    OPERATION_COMPLETE: Any
    CONFIRM: Any
    ERROR: Any
    WARNING: Any

# MessageType
class PrintType(Enum):
    INFO: Any
    ERROR: Any
    WARNING: Any

# BrowserType
class BrowserType(Enum):
    FILE: Any
    DIRECTORY: Any

# Text Style
class TextStyle(Enum):
    EDITABLE: Any
    READ_ONLY: Any
    UNSELECTABLE: Any

# Text Type
class TextType(Enum):
    PLAIN: Any
    MARKDOWN: Any
    HTML: Any

# PyFlame
class _PyFlame:
    # Get the main window resolution.
    def window_resolution() -> Any: ...
    # Pause
    def pause(seconds) -> None: ...
    # Python Package Local Install
    def python_package_local_install(package) -> bool: ...
    def cursor_busy() -> None: ...
    def cursor_restore() -> None: ...
    # Print Title
    def print_title(text) -> None: ...
    # Create Temp Folder
    def create_temp_folder(folder_name) -> str: ...
    # Cleanup Temp Folder
    def cleanup_temp_folder(folder_name) -> None: ...
    # Verify Script Install
    def verify_script_install(additional_files) -> bool: ...
    # Create Media Panel Library
    def create_media_panel_libraries(library_structure) -> None: ...
    # Create Media Panel Folder
    def create_media_panel_folder(folder_name, folder_structure: dict[str, Any], dest: flame.PyFolder | flame.PyLibrary, shot_name_tag: str = ...) -> None: ...
    # Create Media Panel Folders
    def create_media_panel_folders(folder_list, folder_structure: dict[str, Any], dest: flame.PyFolder | flame.PyLibrary) -> None: ...
    # Create File System Folder
    def create_file_system_folder(folder_name, folder_structure: dict[str, Any], dest_path: str, skip_existing: bool = ...) -> None: ...
    # Create File System Folders
    def create_file_system_folders(folder_list, folder_structure: dict[str, Any], dest_path: str) -> None: ...
    # Copy to Clipboard
    def copy_to_clipboard(value) -> None: ...
    # Print
    def print(text, indent: int = ..., print_type: Any = ..., new_line: bool = ..., arrow: bool = ..., underline: bool = ..., double_underline: bool = ..., text_color: TextColor | None = ..., time: int = ..., print_to_flame: bool = ..., script_name: str = ...) -> None: ...
    # Print Dict
    def print_dict(dict_data, indent: int = ...) -> None: ...
    # Print JSON
    def print_json(json_data, indent: Any = ...) -> None: ...
    # Print List
    def print_list(list_name, list_items: list, indent: Any = ..., time: int = ..., script_name: str = ...) -> None: ...
    # Generate Unique Node Names
    def generate_unique_node_names(node_names, existing_node_names: list[str]) -> list[str]: ...
    # Generate Unique Names
    def generate_unique_name(value, existing_names: list[str]) -> str: ...
    # Get Flame Version
    def get_flame_version() -> float: ...
    # Get Flame Python Packages Path
    def get_flame_python_packages_path(print_path) -> str: ...
    # File Browser
    def file_browser(path, title: str | None = ..., extension: str | List[str] | None = ..., select_directory: bool = ..., multi_selection: bool = ..., include_resolution: bool = ..., use_flame_browser: bool = ..., window_to_hide: QtWidgets.QWidget | list[QtWidgets.QWidget] | None = ...) -> str | list | None: ...
    # Open in Finder
    def open_in_finder(path) -> None: ...
    # Raise Type Error
    def raise_type_error(source_name, arg_name: str | None = ..., expected_type: str | None = ..., actual_value: Any = ..., error_message: str | None = ..., time: int = ...) -> None: ...
    # Raise Value Error
    def raise_value_error(source_name, arg_name: str = ..., expected_value: Any = ..., actual_value: Any = ..., error_message: str = ..., time: int = ...) -> None: ...
    # Refresh Hooks
    def refresh_hooks(script_name) -> None: ...
    # Resolve Path Tokens
    def resolve_path_tokens(tokenized_path, flame_pyobject: Any = ..., date: Any = ...) -> str: ...
    # Resolve Path Tokens
    def resolve_tokens(tokenized_string, flame_pyobject: Any = ..., date: Any = ...) -> str: ...
    # Resolve Shot Name
    def resolve_shot_name(name) -> str: ...
    # Untar
    def untar(tar_file_path, untar_path: str, sudo_password: str | None = ...) -> bool: ...
    # GUI Resize
    def gui_resize(value) -> int: ...
    # Font Resize
    def font_resize(value) -> int: ...
    # Get Export Preset Version
    def get_export_preset_version(preset_path) -> Tuple[str, str]: ...
    # Update Export Preset
    def update_export_preset(preset_path) -> None: ...
    # Iterate Name
    def iterate_name(existing_names, new_name: str) -> str: ...
    # Get Export Preset Names
    def get_export_preset_names() -> List[str]: ...
    # Convert Export Preset Name to Path
    def convert_export_preset_name_to_path(export_preset_name) -> str: ...
    # Set Shot Tagging
    def set_shot_tagging(pyobject, shot_name: str, append: bool = ...) -> None: ...
    # Find By Tag
    def find_by_tag(pyobject, target_tag: str, sorted: bool = ...) -> Any: ...
    # Shot Name From Clip
    def shot_name_from_clip(clip) -> str: ...
    # Get Media Panel Folder
    def get_media_panel_shot_folder(shot_name, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str) -> flame.PyFolder | None: ...
    # Move to Shot Folder
    def move_to_shot_folder(shot_name, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str, expand_dest_folder: bool = ...) -> None: ...
    # Copy to Shot Folder
    def copy_to_shot_folder(shot_name, pyobject: flame.PyClip | flame.PyBatch | flame.PyDesktop, search_location: flame.PyLibrary | flame.PyFolder, dest_folder_path: str, expand_dest_folder: bool = ...) -> None: ...

pyflame: Any
# Load Font
def _load_font() -> Any: ...

# PyFlameToolTip
class PyFlameToolTip:
    def __init__(self, parent_widget: QtWidgets.QWidget, text: str = ..., delay: int = ..., duration: int = ...) -> None: ...
    # Stop timers when the helper is deleted to avoid lingering signals.
    def __del__(self) -> Any: ...
    @property
    def widget(self) -> QtWidgets.QWidget: ...
    def widget(self, value: QtWidgets.QWidget) -> Any: ...
    @property
    def text(self) -> str: ...
    def text(self, value: str) -> Any: ...
    @property
    def delay(self) -> int: ...
    def delay(self, value: int) -> Any: ...
    @property
    def duration(self) -> int: ...
    def duration(self, value: int) -> Any: ...
    # Enter Event
    def enter_event(self) -> Any: ...
    # Leave Event
    def leave_event(self) -> Any: ...
    # Show Tooltip
    def _show_tooltip(self) -> Any: ...
    def _hide_tooltip(self) -> Any: ...

# PyFlameConfig
class PyFlameConfig:
    def __init__(self, config_values: Dict[str, Any], config_path: str = ..., script_name: str = ...) -> Any: ...
    # Load Config
    def load_config(self) -> None: ...
    # Save Config
    def save_config(self, config_values: Dict[str, Any] | None = ..., config_path: str | None = ...) -> None: ...
    # Get Config Values
    def get_config_values(config_path) -> Dict[str, Any]: ...

# PyFlameButton
class PyFlameButton(QtWidgets.QPushButton):
    def __init__(self, text: str = ..., connect: Callable[..., None] = ..., color: Color = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Color
    @property
    def color(self) -> Color: ...
    # Color
    def color(self, value: Color) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Connect Callback
    def connect_callback(self, callback: Callable) -> None: ...
    # Set Style Sheet
    def _set_stylesheet(self, color: Color) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameEntry
class PyFlameEntry(QtWidgets.QLineEdit):
    def __init__(self, text: str = ..., align: Align = ..., text_changed: Callable[..., None] | None = ..., placeholder_text: str = ..., read_only: bool = ..., password_echo: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Align
    @property
    def align(self) -> Align: ...
    # Align
    def align(self, value: Align) -> None: ...
    # Placeholder Text
    @property
    def placeholder_text(self) -> str | None: ...
    # Placeholder Text
    def placeholder_text(self, value: str | None) -> None: ...
    # Read Only
    @property
    def read_only(self) -> bool: ...
    # Read Only
    def read_only(self, value: bool) -> None: ...
    # Password Echo
    @property
    def password_echo(self) -> bool: ...
    # Password Echo
    def password_echo(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Set Focus
    def set_focus(self) -> None: ...
    # Text Changed
    def text_changed(self, connected_function: Callable) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self, read_only: Any) -> None: ...
    def mousePressEvent(self, event: Any) -> Any: ...
    def mouseMoveEvent(self, event: Any) -> Any: ...
    def keyPressEvent(self, event: Any) -> Any: ...
    def mouseDoubleClickEvent(self, event: Any) -> Any: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...
    # Event Filter
    def eventFilter(self, obj: Any, event: Any) -> Any: ...
    # Show Full Entry Text
    def _show_full_entry_text(self) -> Any: ...
    # Hide Full Entry Text
    def _hide_full_entry_text(self) -> Any: ...

# PyFlameEntryBrowser
class PyFlameEntryBrowser(QtWidgets.QLineEdit):
    clicked: Any
    def __init__(self, path: str, placeholder_text: str | None = ..., browser_type: BrowserType = ..., browser_ext: List[str] = ..., browser_title: str = ..., window_to_hide: list[QtWidgets.QWidget] | QtWidgets.QWidget | None = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> Any: ...
    # Path
    @property
    def path(self) -> str: ...
    # Path
    def path(self, value: str) -> None: ...
    # Placeholder Text
    @property
    def placeholder_text(self) -> str | None: ...
    # Placeholder Text
    def placeholder_text(self, value: str | None) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Connect Callback
    def connect_callback(self, callback: Callable) -> None: ...
    # Open File Browser
    def open_file_browser(self, browser_type: BrowserType, browser_ext: list, browser_title: str, window_to_hide: list[QtWidgets.QWidget] | QtWidgets.QWidget | None = ...) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    def mousePressEvent(self, event: Any) -> Any: ...
    def mouseMoveEvent(self, event: Any) -> Any: ...
    def keyPressEvent(self, event: Any) -> Any: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameLabel
class PyFlameLabel(QtWidgets.QLabel):
    def __init__(self, text: str = ..., style: Style = ..., align: Align | None = ..., underline_color: Color = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., font_size: int | None = ..., parent: QtWidgets.QWidget | None = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Style
    @property
    def style(self) -> Style: ...
    # Style
    def style(self, value: Style) -> None: ...
    # Align
    @property
    def align(self) -> Align | None: ...
    # Align
    def align(self, value: Align | None) -> None: ...
    # Underline Color
    @property
    def underline_color(self) -> Color: ...
    # Underline Color
    def underline_color(self, value: Color) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int | None: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int | None: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Font Size
    @property
    def font_size(self) -> int | None: ...
    # Font Size
    def font_size(self, value: int | None) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    # Set Underline Stylesheet
    def _set_underline_stylesheet(self) -> None: ...

# PyFlameListWidget
class PyFlameListWidget(QtWidgets.QListWidget):
    def __init__(self, items: List[str] = ..., alternating_row_colors: bool = ..., multi_selection: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Items
    @property
    def items(self) -> List[str]: ...
    # Items
    def items(self, values: List[str]) -> None: ...
    # Selected Items
    @property
    def selected_items(self) -> List[QtWidgets.QListWidgetItem]: ...
    # Alternating Row Colors
    @property
    def alternating_row_colors(self) -> bool: ...
    # Alternating Row Colors
    def alternating_row_colors(self, value: bool) -> None: ...
    # Multi Selection
    @property
    def multi_selection(self) -> None: ...
    # Multi Selection
    def multi_selection(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Add Items
    def add_items(self, items: List[str]) -> None: ...
    # Replace Items
    def replace_items(self, items: List[str]) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    # Mouse Press Event
    def mousePressEvent(self, event: QtGui.QMouseEvent) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlamePushButton
class PyFlamePushButton(QtWidgets.QPushButton):
    def __init__(self, text: str = ..., checked: bool = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Checked
    @property
    def checked(self) -> bool: ...
    # Checked
    def checked(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Connect Callback
    def connect_callback(self, callback: Callable) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameMenu
class PyFlameMenu(QtWidgets.QPushButton):
    def __init__(self, text: str = ..., align: Align = ..., menu_options: List[str] = ..., menu_indicator: bool = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Align
    @property
    def align(self) -> Align: ...
    # Align
    def align(self, value: Align) -> None: ...
    # Menu Options
    @property
    def menu_options(self) -> List[str]: ...
    # Set Menu Options
    def menu_options(self, options: List[str]) -> None: ...
    # Menu Indicator
    @property
    def menu_indicator(self) -> bool: ...
    # Menu Indicator
    def menu_indicator(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Update Menu
    def update_menu(self, text: str, menu_options: list[str], connect: Callable[..., None] | None = ...) -> None: ...
    # Refresh Menu
    def refresh_menu(self) -> None: ...
    # Match Menu Width
    def _match_push_button_width(self) -> Any: ...
    def _create_menu(self, menu: Any, connect: Any) -> Any: ...
    # Set Stylesheet
    def _set_button_stylesheet(self) -> None: ...
    # Set Stylesheet
    def _set_menu_stylesheet(self) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameColorMenu
class PyFlameColorMenu(QtWidgets.QPushButton):
    def __init__(self, color_options: Dict[str, Tuple[float, float, float, float]] = ..., color: str = ..., menu_indicator: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Color Options
    @property
    def color_options(self) -> Dict[str, Tuple[float, float, float, float]]: ...
    # Color Options
    def color_options(self, color_options: Dict[str, Tuple[float, float, float, float]]) -> None: ...
    # Color
    @property
    def color(self) -> str: ...
    # Set Color
    def color(self, value: str) -> None: ...
    # Color Value
    @property
    def color_value(self) -> Tuple[float, float, float, float]: ...
    # Menu Indicator
    @property
    def menu_indicator(self) -> bool: ...
    # Menu Indicator
    def menu_indicator(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Set Color
    def _set_color(self, color: str) -> None: ...
    # Generate Color Icon
    def _generate_color_icon(self, color_value: Tuple[float, float, float, float]) -> QtGui.QIcon: ...
    # Create Menu
    def _create_menu(self, color_name: Any) -> None: ...
    # Match Menu Width
    def _match_push_button_width(self) -> Any: ...
    # Set Button Stylesheet
    def _set_button_stylesheet(self, menu_indicator: Any) -> None: ...
    # Set Menu Stylesheet
    def _set_menu_stylesheet(self) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameTokenMenu
class PyFlameTokenMenu(QtWidgets.QPushButton):
    def __init__(self, text: str = ..., token_dict: Dict[str, str] | None = ..., token_dest: PyFlameEntry | None = ..., clear_dest: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Token Dictionary
    @property
    def token_dict(self) -> Dict[str, str]: ...
    # Token Dictionary
    def token_dict(self, value: Dict[str, str]) -> None: ...
    # Token Destination
    @property
    def token_dest(self) -> Any: ...
    # Token Destination
    def token_dest(self, value: PyFlameEntry) -> None: ...
    # Clear Destination
    @property
    def clear_dest(self) -> bool: ...
    # Clear Destination
    def clear_dest(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Add Menu Options
    def add_menu_options(self, new_options: Dict[str, str]) -> Any: ...
    # Build Token Menu
    def _build_token_menu(self) -> Any: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    def _set_menu_stylesheet(self) -> Any: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameSlider
class PyFlameSlider(QtWidgets.QLineEdit):
    def __init__(self, min_value: int = ..., max_value: int = ..., start_value: int = ..., rate: int | float = ..., connect: Callable[..., None] | None = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Minimum Value
    @property
    def min_value(self) -> int | float: ...
    # Minimum Value
    def min_value(self, value: int | float) -> None: ...
    # Maximum Value
    @property
    def max_value(self) -> int | float: ...
    # Maximum Value
    def max_value(self, value: int | float) -> None: ...
    # Value
    @property
    def value(self) -> int | float: ...
    # Value
    def value(self, value: int | float) -> None: ...
    # Value (String)
    @property
    def value_str(self) -> str: ...
    # Rate
    @property
    def rate(self) -> int | float: ...
    # Rate
    def rate(self, value: int | float) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Connect Callback
    def connect_callback(self, callback: Callable) -> None: ...
    def _calculator(self) -> Any: ...
    def _value_changed(self) -> Any: ...
    def mousePressEvent(self, event: Any) -> Any: ...
    def mouseReleaseEvent(self, event: Any) -> Any: ...
    def mouseMoveEvent(self, event: Any) -> Any: ...
    def getStepsMultiplier(self, event: Any) -> Any: ...
    def setMinimum(self, value: Any) -> Any: ...
    def setMaximum(self, value: Any) -> Any: ...
    def setValue(self, value: Any) -> Any: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameTable
class PyFlameTable(QtWidgets.QTableView):
    def __init__(self, csv_file_path: str | None = ..., alternating_row_colors: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # CSV File Path
    @property
    def csv_file_path(self) -> str | None: ...
    # Alternating Row Colors
    @property
    def alternating_row_colors(self) -> bool: ...
    # Alternating Row Colors
    def alternating_row_colors(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Load CSV
    def load_csv(self, csv_file_path: str | None = ...) -> None: ...
    # Save CSV File
    def save_csv_file(self, csv_file_path: str) -> None: ...
    # Rename Column Header
    def _rename_column_header(self, index: int) -> None: ...
    # Rename Selected Cells
    def _rename_selected_cells(self) -> None: ...
    # Show Right-Click Menu for Rows
    def _show_row_menu(self, position: tuple) -> None: ...
    # Show Right-Click Menu for Columns
    def _show_column_menu(self, position: tuple) -> None: ...
    # Add Row
    def _add_row(self) -> None: ...
    # Delete Selected Rows
    def _delete_selected_rows(self) -> None: ...
    # Add Column
    def _add_column(self) -> None: ...
    # Delete Selected Columns
    def _delete_selected_columns(self) -> None: ...
    # Block Column Selection
    def _block_column_selection(self, event: Any) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    # Set Menu Stylesheet
    def _set_menu_stylesheet(self) -> None: ...
    # Custom Context Menu on Right-Click for Table Body
    def contextMenuEvent(self, event: Any) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameTabWidget
class PyFlameTabWidget(QtWidgets.QTabWidget):
    def __init__(self, tab_names: list[str] = ..., grid_layout_columns: int = ..., grid_layout_rows: int = ..., grid_layout_column_width: int = ..., grid_layout_row_height: int = ..., grid_layout_adjust_column_widths: dict[int, int] = ..., grid_layout_adjust_row_heights: dict[int, int] = ..., tab_label_width: int = ..., tab_label_height: int = ..., enabled: bool = ..., parent: QtWidgets.QWidget | None = ...) -> Any: ...
    # Tab Names
    @property
    def tab_names(self) -> list[str]: ...
    # Tab Names
    def tab_names(self, value: list[str]) -> None: ...
    # Grid Layout Columns
    @property
    def grid_layout_columns(self) -> int: ...
    # Grid Layout Columns
    def grid_layout_columns(self, value: int) -> None: ...
    # Grid Layout Rows
    @property
    def grid_layout_rows(self) -> int: ...
    # Grid Layout Rows
    def grid_layout_rows(self, value: int) -> None: ...
    # Grid Layout Column Width
    @property
    def grid_layout_column_width(self) -> int: ...
    # Grid Layout Column Width
    def grid_layout_column_width(self, value: int) -> None: ...
    # Grid Layout Row Height
    @property
    def grid_layout_row_height(self) -> int: ...
    # Grid Layout Row Height
    def grid_layout_row_height(self, value: int) -> None: ...
    # Grid Layout Adjust Column Widths
    @property
    def grid_layout_adjust_column_widths(self) -> dict[int, int]: ...
    # Grid Layout Adjust Column Widths
    def grid_layout_adjust_column_widths(self, value: dict[int, int]) -> None: ...
    # Grid Layout Adjust Row Heights
    @property
    def grid_layout_adjust_row_heights(self) -> dict[int, int]: ...
    # Grid Layout Adjust Row Heights
    def grid_layout_adjust_row_heights(self, value: dict[int, int]) -> None: ...
    # Tab Label Width
    @property
    def tab_label_width(self) -> int: ...
    # Tab Label Width
    def tab_label_width(self, value: int) -> None: ...
    # Tab Label Height
    @property
    def tab_label_height(self) -> int: ...
    # Tab Label Height
    def tab_label_height(self, value: int) -> None: ...
    # Add Tab
    def add_tab(self, name: str) -> 'PyFlameTabWidget.TabContainer': ...
    # Get Current Tab Name
    def get_current_tab_name(self) -> str | None: ...
    # Get Current Tab Index
    def get_current_tab_index(self) -> int: ...
    # Set Current Tab
    def set_current_tab(self, tab: str | int) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> Any: ...

# PyFlameTextEdit
class PyFlameTextEdit(QtWidgets.QTextEdit):
    def __init__(self, text: str = ..., text_type: TextType = ..., text_style: TextStyle = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text Type
    @property
    def text_type(self) -> TextType: ...
    # Text Type
    def text_type(self, value: TextType) -> Any: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> Any: ...
    # Text String
    @property
    def text_str(self) -> str: ...
    # Text String
    def text_str(self, value: str) -> Any: ...
    # Text Style
    @property
    def text_style(self) -> TextStyle: ...
    # Text Style
    def text_style(self, value: TextStyle) -> Any: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> Any: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameTextBrowser
class PyFlameTextBrowser(QtWidgets.QTextBrowser):
    def __init__(self, text: str = ..., text_type: TextType = ..., text_style: TextStyle = ..., open_external_links: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Text Type
    @property
    def text_type(self) -> TextType: ...
    # Text Type
    def text_type(self, value: TextType) -> Any: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> Any: ...
    # Text String
    @property
    def text_str(self) -> str: ...
    # Text String
    def text_str(self, value: str) -> Any: ...
    # Text Style
    @property
    def text_style(self) -> TextStyle: ...
    # Text Style
    def text_style(self, value: TextStyle) -> Any: ...
    # Open External Links
    @property
    def open_external_links(self) -> bool: ...
    # Open External Links
    def open_external_links(self, value: bool) -> Any: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> Any: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameTreeWidget
class PyFlameTreeWidget(QtWidgets.QTreeWidget):
    def __init__(self, column_names: List[str], sort: bool = ..., tree_dict: Dict[str, Dict[str, str]] = ..., tree_list: List[str] = ..., top_level_item: str | None = ..., connect: Callable[..., None] | None = ..., update_connect: Callable[..., None] | None = ..., top_level_editable: bool = ..., allow_children: bool = ..., min_items: int = ..., alternating_row_colors: bool = ..., elide_text: bool = ..., enabled: bool = ..., width: int | None = ..., height: int | None = ..., tooltip: str | None = ..., tooltip_delay: int = ..., tooltip_duration: int = ...) -> None: ...
    # Column Names
    @property
    def column_names(self) -> List[str]: ...
    # Column Names
    def column_names(self, value: List[str]) -> None: ...
    # Sort
    @property
    def sort(self) -> bool: ...
    # Sort
    def sort(self, value: bool) -> None: ...
    # Tree Dict
    @property
    def tree_dict(self) -> Dict[str, Dict[str, str]] | None: ...
    # Tree Dict
    def tree_dict(self, value: Dict[str, Dict[str, str]]) -> None: ...
    # Top Level Item
    @property
    def top_level_item(self) -> str: ...
    # Top Level Item
    def top_level_item(self, value: str) -> None: ...
    # Tree List
    @property
    def tree_list(self) -> List[str] | None: ...
    # Tree List
    def tree_list(self, value: List[str]) -> None: ...
    # Tree List No Root
    @property
    def tree_list_no_root(self) -> List[str]: ...
    # Connect Callback
    @property
    def connect_callback(self) -> Callable[..., None]: ...
    # Connect Callback
    def connect_callback(self, value: Callable[..., None]) -> None: ...
    # Update Connect Callback
    @property
    def update_connect_callback(self) -> Callable[..., None]: ...
    # Update Connect Callback
    def update_connect_callback(self, value: Callable[..., None]) -> None: ...
    # Alternating Row Colors
    @property
    def alternating_row_colors(self) -> bool: ...
    # Alternating Row Colors
    def alternating_row_colors(self, value: bool) -> None: ...
    # Allow Children
    @property
    def allow_children(self) -> bool: ...
    # Allow Children
    def allow_children(self, value: bool) -> None: ...
    # Min Items
    @property
    def min_items(self) -> int: ...
    # Min Items
    def min_items(self, value: int) -> None: ...
    # Top Level Editable
    @property
    def top_level_editable(self) -> bool: ...
    # Top Level Editable
    def top_level_editable(self, value: bool) -> None: ...
    # Elide Text
    @property
    def elide_text(self) -> bool: ...
    # Elide Text
    def elide_text(self, value: bool) -> None: ...
    # Enabled
    @property
    def enabled(self) -> bool: ...
    # Enabled
    def enabled(self, value: bool) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    # Tooltip
    @property
    def tooltip(self) -> str | None: ...
    # Tooltip
    def tooltip(self, value: str | None) -> None: ...
    # Tooltip Delay
    @property
    def tooltip_delay(self) -> int: ...
    # Tooltip Delay
    def tooltip_delay(self, value: int) -> None: ...
    # Tooltip Duration
    @property
    def tooltip_duration(self) -> int: ...
    # Tooltip Duration
    def tooltip_duration(self, value: int) -> None: ...
    # All Item Paths
    @property
    def all_item_paths(self) -> list: ...
    # All Item Paths No Root
    @property
    def all_item_paths_no_root(self) -> list: ...
    # Item Path
    @property
    def item_path(self) -> str: ...
    # Item Paths
    @property
    def item_paths(self) -> List[str]: ...
    # Selected Item
    @property
    def selected_item(self) -> str: ...
    # Fill Tree Dict
    def fill_tree_dict(self, tree_dict: Dict[str, str], editable: bool = ...) -> None: ...
    # Fill Tree List
    def fill_tree_list(self, tree_list: List[str]) -> None: ...
    # Add Item
    def add_item(self, item_name: str) -> None: ...
    # Add Item With Columns
    def add_item_with_columns(self, item: list[str]) -> QtWidgets.QTreeWidgetItem: ...
    # Delete Item
    def delete_item(self) -> None: ...
    # Sort Items
    def sort_items(self) -> None: ...
    # Color Item
    def color_item(self, item: Any, color: Any) -> None: ...
    # Set Fixed Column Headers
    def set_fixed_column_headers(self) -> None: ...
    # Clear
    def clear(self) -> None: ...
    # Update
    def update(self) -> None: ...
    # Trigger Callback
    def _trigger_callback(self) -> None: ...
    # On Item Collapsed
    def _on_item_collapsed(self, item: Any) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    def enterEvent(self, event: Any) -> Any: ...
    def leaveEvent(self, event: Any) -> Any: ...

# PyFlameProgressBarWidget
class PyFlameProgressBarWidget(QtWidgets.QProgressBar):
    def __init__(self, total_tasks: int = ..., processing_task: int = ..., bar_color: Color = ..., bar_height: int = ..., parent: QtWidgets.QWidget | None = ...) -> None: ...
    # Total Tasks
    @property
    def total_tasks(self) -> int: ...
    # Total Tasks
    def total_tasks(self, value: int) -> None: ...
    # Processing Task
    @property
    def processing_task(self) -> int: ...
    # Processing Task
    def processing_task(self, value: int) -> None: ...
    # Bar Color
    @property
    def bar_color(self) -> Color: ...
    # Bar Color
    def bar_color(self, value: Color) -> None: ...
    # Bar Height
    @property
    def bar_height(self) -> int: ...
    # Bar Height
    def bar_height(self, value: int) -> None: ...

# PyFlameButtonGroup
class PyFlameButtonGroup(QtWidgets.QButtonGroup):
    def __init__(self, button_group: list, set_exclusive: bool = ...) -> None: ...
    # Button Group
    @property
    def button_group(self) -> list: ...
    # Button Group
    def button_group(self, value: list) -> None: ...
    # Set Exclusive
    @property
    def set_exclusive(self) -> bool: ...
    # Set Exclusive
    def set_exclusive(self, value: bool) -> None: ...

# PyFlameHorizontalLine
class PyFlameHorizontalLine(QtWidgets.QFrame):
    def __init__(self, color: Color = ..., width: int | None = ..., height: int | None = ...) -> None: ...
    # Color
    @property
    def color(self) -> Color: ...
    # Color
    def color(self, value: Any) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    def _set_stylesheet(self) -> None: ...

# PyFlameVerticalLine
class PyFlameVerticalLine(QtWidgets.QFrame):
    def __init__(self, color: Color = ..., width: int | None = ..., height: int | None = ...) -> None: ...
    # Color
    @property
    def color(self) -> Color: ...
    # Color
    def color(self, value: Any) -> None: ...
    # Width
    @property
    def width(self) -> int: ...
    # Width
    def width(self, value: int | None) -> None: ...
    # Height
    @property
    def height(self) -> int: ...
    # Height
    def height(self, value: int | None) -> None: ...
    def _set_style_sheet(self) -> None: ...

# PyFlameGridLayout
class PyFlameGridLayout(QtWidgets.QGridLayout):
    def __init__(self, columns: int = ..., rows: int = ..., column_width: int = ..., row_height: int = ..., adjust_column_widths: dict[int, int] = ..., adjust_row_heights: dict[int, int] = ...) -> None: ...

# PyFlameHBoxLayout
class PyFlameHBoxLayout(QtWidgets.QHBoxLayout):
    def __init__(self) -> None: ...
    # Set Spacing
    def setSpacing(self, spacing: int) -> None: ...
    # Add Spacing
    def addSpacing(self, spacing: int) -> None: ...
    # Set Contents Margins
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...

# PyFlameVBoxLayout
class PyFlameVBoxLayout(QtWidgets.QVBoxLayout):
    def __init__(self) -> None: ...
    # Set Spacing
    def setSpacing(self, spacing: int) -> None: ...
    # Add Spacing
    def addSpacing(self, spacing: int) -> None: ...
    # Set Contents Margins
    def setContentsMargins(self, left: int, top: int, right: int, bottom: int) -> None: ...

# PyFlameWindow
class PyFlameWindow(QtWidgets.QDialog):
    def __init__(self, parent: QtWidgets.QWidget | None, title: str = ..., title_style: Style = ..., title_align: Align = ..., title_underline_color: Color = ..., title_height: int = ..., title_font_size: int = ..., message_bar: bool = ..., line_color: Color = ..., tab_order: list[QtWidgets.QWidget] | None = ..., return_pressed: Callable[..., None] | None = ..., escape_pressed: Callable[..., None] | None = ..., grid_layout_columns: int = ..., grid_layout_rows: int = ..., grid_layout_column_width: int = ..., grid_layout_row_height: int = ..., grid_layout_adjust_column_widths: dict[int, int] = ..., grid_layout_adjust_row_heights: dict[int, int] = ..., window_margins: int | tuple[int, int, int, int] = ...) -> None: ...
    # Line Color
    @property
    def line_color(self) -> Color: ...
    # Line Color
    def line_color(self, value: Color) -> None: ...
    # Title
    @property
    def title(self) -> str: ...
    # Title
    def title(self, value: str) -> None: ...
    # Title Style
    @property
    def title_style(self) -> Style: ...
    # Title Style
    def title_style(self, value: Style) -> None: ...
    # Title Align
    @property
    def title_align(self) -> Align: ...
    # Title Align
    def title_align(self, value: Align) -> None: ...
    # Title Underline Color
    @property
    def title_underline_color(self) -> Color: ...
    # Title Underline Color
    def title_underline_color(self, value: Color) -> None: ...
    # Title Height
    @property
    def title_height(self) -> int: ...
    # Title Height
    def title_height(self, value: int) -> None: ...
    # Title Font Size
    @property
    def title_font_size(self) -> int: ...
    # Title Font Size
    def title_font_size(self, value: int) -> None: ...
    # Message Bar Text
    @property
    def message_bar_text(self) -> str: ...
    # Message Bar Text
    def message_bar_text(self, value: str) -> None: ...
    # Tab Order
    @property
    def tab_order(self) -> Any: ...
    # Tab Order
    def tab_order(self, tab_order: Any) -> Any: ...
    # Return Pressed
    @property
    def return_pressed(self) -> Callable[[], None] | None: ...
    # Return Pressed
    def return_pressed(self, value: Callable[[], None] | None) -> None: ...
    # Escape Pressed
    @property
    def escape_pressed(self) -> Callable[[], None] | None: ...
    # Escape Pressed
    def escape_pressed(self, value: Callable[[], None] | None) -> None: ...
    # Grid Layout Columns
    @property
    def grid_layout_columns(self) -> int: ...
    # Grid Layout Columns
    def grid_layout_columns(self, value: int) -> None: ...
    # Grid Layout Rows
    @property
    def grid_layout_rows(self) -> int: ...
    # Grid Layout Rows
    def grid_layout_rows(self, value: int) -> None: ...
    # Grid Layout Column Width
    @property
    def grid_layout_column_width(self) -> int: ...
    # Grid Layout Column Width
    def grid_layout_column_width(self, value: int) -> None: ...
    # Grid Layout Row Height
    @property
    def grid_layout_row_height(self) -> int: ...
    # Grid Layout Row Height
    def grid_layout_row_height(self, value: int) -> None: ...
    # Grid Layout Adjust Column Widths
    @property
    def grid_layout_adjust_column_widths(self) -> dict[int, int]: ...
    # Grid Layout Adjust Column Widths
    def grid_layout_adjust_column_widths(self, value: dict[int, int]) -> None: ...
    # Grid Layout Adjust Row Heights
    @property
    def grid_layout_adjust_row_heights(self) -> dict[int, int]: ...
    # Grid Layout Adjust Row Heights
    def grid_layout_adjust_row_heights(self, value: dict[int, int]) -> None: ...
    # Window Margins
    @property
    def window_margins(self) -> tuple[int, int, int, int]: ...
    # Window Margins
    def window_margins(self, value: int | tuple[int, int, int, int]) -> None: ...
    # Center Window
    def center_window(self) -> None: ...
    # Print
    def print(self, message: str) -> None: ...
    # Set Stylesheet
    def _set_stylesheet(self) -> None: ...
    # Mouse Press Event
    def mousePressEvent(self, event: Any) -> Any: ...
    # Mouse Move Event
    def mouseMoveEvent(self, event: Any) -> Any: ...
    # Key Press Event
    def keyPressEvent(self, event: Any) -> Any: ...
    # Paint Event
    def paintEvent(self, event: Any) -> Any: ...

# PyFlameInputDialog
class PyFlameInputDialog:
    def __init__(self, parent: PyFlameWindow | None, text: str = ..., label_text: str = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color = ..., message_bar: bool = ...) -> Any: ...
    # Text
    @property
    def text(self) -> str | None: ...
    # Text
    def text(self, value: str) -> None: ...
    # Message Bar Text
    @property
    def message_bar_text(self) -> str: ...
    # Message Bar Text
    def message_bar_text(self, value: str) -> None: ...
    # Label Text
    @property
    def label_text(self) -> str: ...
    # Label Text
    def label_text(self, value: str) -> None: ...
    # Title
    @property
    def title(self) -> str: ...
    # Title
    def title(self, value: str) -> None: ...
    # Title Style
    @property
    def title_style(self) -> Style: ...
    # Title Style
    def title_style(self, value: Style) -> None: ...
    # Title Align
    @property
    def title_align(self) -> Align | None: ...
    # Title Align
    def title_align(self, value: Align | None) -> None: ...
    # Line Color
    @property
    def line_color(self) -> Color: ...
    # Line Color
    def line_color(self, value: Color) -> None: ...
    # Confirm
    def _confirm(self) -> None: ...
    # Cancel
    def _cancel(self) -> None: ...

# PyFlameMessageWindow
class PyFlameMessageWindow:
    def __init__(self, parent: PyFlameWindow | None, message: str = ..., message_type: MessageType = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color | None = ..., message_bar: Any = ..., duration: int = ...) -> None: ...
    def __bool__(self) -> Any: ...
    # Message
    @property
    def message(self) -> Any: ...
    # Message
    def message(self, value: str) -> None: ...
    # Message Type
    @property
    def message_type(self) -> Any: ...
    # Message Type
    def message_type(self, value: MessageType) -> None: ...
    # Title
    @property
    def title(self) -> str: ...
    # Title
    def title(self, value: str) -> None: ...
    # Title Style
    @property
    def title_style(self) -> Style: ...
    # Title Style
    def title_style(self, value: Style) -> None: ...
    # Title Align
    @property
    def title_align(self) -> Align: ...
    # Title Align
    def title_align(self, value: Align | None) -> None: ...
    # Line Color
    @property
    def line_color(self) -> Color | None: ...
    # Line Color
    def line_color(self, value: Color | None) -> None: ...
    # Message Bar Text
    @property
    def message_bar_text(self) -> str: ...
    # Message Bar Text
    def message_bar_text(self, value: str) -> None: ...
    # Duration
    @property
    def duration(self) -> int: ...
    # Title Style
    def duration(self, value: int) -> None: ...
    # Confirmed
    @property
    def confirmed(self) -> bool: ...
    # Set the confirmed status of the message.
    def confirmed(self, value: bool) -> None: ...
    # Print
    def _message_print(self, message: str, title: str, duration: int) -> Any: ...
    # Cancel
    def cancel(self) -> None: ...
    # Confirm
    def confirm(self) -> None: ...
    # Close
    def close(self) -> None: ...

# PyFlamePasswordWindow
class PyFlamePasswordWindow:
    def __init__(self, parent: PyFlameWindow | None, text: str = ..., user_name_prompt: bool = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color | None = ..., message_bar: bool = ...) -> Any: ...
    # Text
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Title
    @property
    def title(self) -> str: ...
    # Title
    def title(self, value: str) -> None: ...
    # Title Style
    @property
    def title_style(self) -> Style: ...
    # Title Style
    def title_style(self, value: Style) -> None: ...
    # Title Align
    @property
    def title_align(self) -> Align: ...
    # Title Align
    def title_align(self, value: Align | None) -> None: ...
    # Line Color
    @property
    def line_color(self) -> Color | None: ...
    # Line Color
    def line_color(self, value: Color | None) -> None: ...
    # Message Bar Text
    @property
    def message_bar_text(self) -> str: ...
    # Message Bar Text
    def message_bar_text(self, value: str) -> None: ...
    # Password
    @property
    def password(self) -> str: ...
    # Password
    def password(self, value: str = ...) -> None: ...
    # Username
    @property
    def username(self) -> str: ...
    # User Name
    def username(self, value: str = ...) -> None: ...
    # Test Password
    def _test_password(self) -> Any: ...
    # Confirm
    def _confirm(self) -> Any: ...
    # Cancel
    def _cancel(self) -> Any: ...

# PyFlameProgressWindow
class PyFlameProgressWindow:
    def __init__(self, parent: PyFlameWindow | None, task: str = ..., total_tasks: int = ..., task_progress_message: str = ..., title: str = ..., title_style: Style = ..., title_align: Align | None = ..., line_color: Color = ..., message_bar: bool = ...) -> None: ...
    # Task
    @property
    def text(self) -> str: ...
    # Text
    def text(self, value: str) -> None: ...
    # Task
    @property
    def task(self) -> str: ...
    # Task
    def task(self, value: str) -> None: ...
    # Total Tasks
    @property
    def total_tasks(self) -> int: ...
    # Total Tasks
    def total_tasks(self, value: int) -> None: ...
    # Current Task
    @property
    def current_task(self) -> int: ...
    # Current Task
    def current_task(self, value: int) -> None: ...
    # Title
    @property
    def title(self) -> str: ...
    # Title
    def title(self, value: str) -> None: ...
    # Title Style
    @property
    def title_style(self) -> Style: ...
    # Title Style
    def title_style(self, value: Style) -> None: ...
    # Title Align
    @property
    def title_align(self) -> Align: ...
    # Title Align
    def title_align(self, value: Align | None) -> None: ...
    # Line Color
    @property
    def line_color(self) -> Color: ...
    # Line Color
    def line_color(self, value: Color) -> None: ...
    # Message Bar Text
    @property
    def message_bar_text(self) -> str: ...
    # Message Bar Text
    def message_bar_text(self, value: str) -> None: ...
    def enable_done_button(self) -> Any: ...
    # Close
    def close(self) -> Any: ...
    # Text Append
    def text_append(self, message: str) -> None: ...
    # Tasks Completed
    def tasks_completed(self, done_button_enabled: bool = ..., task_progress_message: str = ..., title: str = ..., text_append: str = ...) -> None: ...
